version: 0.2
phases:
  build:
    commands:
      - nom install
      - npm run build
  post_build:
    commands:
      - aws s3 sync dist s3://${S3_BUCKET_NAME}
      - aws cloudfront create-invalidation --distribution-id ${CLOUDFRONT_DISTRIBUTION_ID} --paths '/*'
