version: 0.2
phases:
  build:
    commands:
      - npm install
      - npm run build
      - ls -la
      - echo ${S3_BUCKET_NAME}
      - echo ${CLOUDFRONT_DISTRIBUTION_ID}
  post_build:
    commands:
      - aws s3 sync dist s3://${S3_BUCKET_NAME}
      - aws cloudfront create-invalidation --distribution-id ${CLOUDFRONT_DISTRIBUTION_ID} --paths '/*'
